### ISSUE TITLE
sjoin right side field values are undefined

### ISSUE THREAD

**Issue by wondie** [chrispahm/spatialmerge#1]
The code below couldn't receive field values of parcel. Thus, the fields of parcel are in the output but their values are undefined. 
`sjoin(buildingGeoJSON, parcel, {how: 'inner', op: 'intersects'});`

**Comment by chrispahm** [comment]
Hey @wondie,

Thanks for raising an issue! Do you have any reproducable example that I can work with?
Best
Christoph

**Comment by wondie** [comment]
@chrispahm sure! Thank you for the quick response. I found the issue. It was because the right featureClass has fields that exists in the right featureClass. Removing the duplicate columns fixed the issue.
